name: E2E Tests

on:
  pull_request:
    branches: [main, develop]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # Build frontend (Next.js)
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Start backend (Express/FastAPI) in background
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Start backend server
        working-directory: ./backend
        run: npm start &

      # Wait a bit for backend to boot
      - name: Wait for backend
        run: sleep 10

      # Install Playwright browsers
      - name: Install Playwright
        working-directory: ./frontend
        run: npx playwright install --with-deps

      # Run Playwright tests
      - name: Run Playwright tests
        working-directory: ./frontend/e2e
        run: npx playwright test --reporter=dot
